version: "3.7"

networks:
  internal:
    name: internal
    driver: bridge

volumes:
  database:

services:
  database:
    image: timescale/timescaledb:latest-pg10
    networks: 
      - internal
    ports:
      - "5432"
    environment:
      POSTGRES_USER: coda
      POSTGRES_PASSWORD: coda
      POSTGRES_DB: coda
    volumes:
      - database:/var/lib/postgresql/data/
  
  server:
    build: .
    command: -cmd=server
    networks:
      - internal
    ports:
      - "8081:8081"
    environment:
      CODA_ENDPOINT: http://YOUR_ENDPOINT
      DATABASE_URL: postgres://coda:coda@database/coda?sslmode=disable
    depends_on:
      - database
  
  worker:
    build: .
    command: -cmd=worker
    networks:    
      - internal
    environment:
      CODA_ENDPOINT: http://YOUR_ENDPOINT
      DATABASE_URL: postgres://coda:coda@database/coda?sslmode=disable
    depends_on:
      - database

  migrate:
    build: .
    command: -cmd=migrate
    networks:
      - internal
    environment:
      CODA_ENDPOINT: http://YOUR_ENDPOINT
      DATABASE_URL: postgres://coda:coda@database/coda?sslmode=disable
    depends_on:
      - database
